-- Operational vehicle records are intentionally not committed.
-- Load them from the ignored scripts/data-vehicles.json file with scripts/seed-db.js.

INSERT INTO checklist_items (vehicle_type, frequency, item_name_th, item_name_en, sort_order) VALUES
  -- Car daily
  ('car', 'daily', 'ความสะอาดและ 5ส ทั้งภายในและภายนอกรถ', 'Cleanliness & 5S inside and outside', 1),
  ('car', 'daily', 'เข็มขัดนิรภัย', 'Seat belt', 2),
  ('car', 'daily', 'เครื่องยนต์ (Breakdown)', 'Engine (Breakdown)', 3),
  ('car', 'daily', 'ประตูรถ', 'Vehicle doors', 4),
  ('car', 'daily', 'ระดับน้ำมันหรือก๊าชเชื้อเพลิง', 'Fuel/gas level', 5),
  ('car', 'daily', 'กระจกมองข้าง', 'Side mirrors', 6),
  ('car', 'daily', 'กระจกมองหลัง', 'Rear-view mirror', 7),
  ('car', 'daily', 'ระบบเบรค (เท้า/มือ)', 'Brakes (foot/hand)', 8),
  ('car', 'daily', 'ระบบสัญญาณเซ็นเซอร์ถอย', 'Reverse sensor', 9),
  ('car', 'daily', 'ระบบกล้องหน้า, ห้องโดยสาร', 'Front/cabin camera', 10),
  ('car', 'daily', 'ไฟเตือน', 'Warning lights', 11),
  ('car', 'daily', 'สัญญาณแตร', 'Horn', 12),
  ('car', 'daily', 'ระบบกล้องหลัง', 'Rear camera', 13),
  ('car', 'daily', 'ระบบกระจกไฟฟ้าห้องโดยสาร', 'Power windows', 14),
  ('car', 'daily', 'ไฟหรี่ - ไฟหน้า', 'Parking/head lights', 15),
  ('car', 'daily', 'ไฟเลี้ยว - ไฟฉุกเฉิน', 'Turn signal/hazard lights', 16),
  ('car', 'daily', 'ไฟระบุความสูงตู้บรรทุก', 'Cargo height indicator lights', 17),
  ('car', 'daily', 'ตัวถังรถ Logo และข้อความของ DHL', 'Body/DHL logo & text', 18),
  ('car', 'daily', 'ตัวถัง ตู้บรรทุก เสียหาย', 'Body/cargo box damage', 19),
  ('car', 'daily', 'ใต้ท้องรถ (รอยน้ำมันรั่ว)', 'Underbody (oil leaks)', 20),
  ('car', 'daily', 'ตู้บรรทุก 7 จุด', 'Cargo box 7-point check', 21),
  ('car', 'daily', 'ไฟหรี่ (ด้านหลัง)', 'Rear parking lights', 22),
  ('car', 'daily', 'ไฟถอย - ไฟเบรค', 'Reverse/brake lights', 23),
  ('car', 'daily', 'ระบบ Lock และเซ็นเซอร์ประตูตู้บรรทุก', 'Cargo door lock & sensor', 24),
  ('car', 'daily', 'อื่นๆ (Tailgate)', 'Others (Tailgate)', 25),
  ('car', 'daily', 'Flyer (Standard & Large)', 'Flyer (Standard & Large)', 26),
  ('car', 'daily', 'Packing list Envelope', 'Packing list Envelope', 27),
  ('car', 'daily', '3 PLY Waybill', '3 PLY Waybill', 28),
  ('car', 'daily', 'Performa Invoice', 'Performa Invoice', 29),
  ('car', 'daily', 'SI Label', 'SI Label', 30),
  ('car', 'daily', 'TDX Label (Pre 9, 10:30, 12)', 'TDX Label (Pre 9, 10:30, 12)', 31),
  ('car', 'daily', 'Exception Card', 'Exception Card', 32),
  ('car', 'daily', 'Courier Notification Card', 'Courier Notification Card', 33),
  ('car', 'daily', 'OPP Tape', 'OPP Tape', 34),
  ('car', 'daily', 'Paper Envelope', 'Paper Envelope', 35),
  ('car', 'daily', 'Box no.2', 'Box no.2', 36),
  ('car', 'daily', 'Box no.3', 'Box no.3', 37),
  ('car', 'daily', 'Box no.4', 'Box no.4', 38),
  ('car', 'daily', 'Box no.5', 'Box no.5', 39),
  ('car', 'daily', 'Box no.6', 'Box no.6', 40),
  ('car', 'daily', 'Box no.7', 'Box no.7', 41),
  ('car', 'daily', 'Box no.8', 'Box no.8', 42),
  ('car', 'daily', 'Brown box 250', 'Brown box 250', 43),
  ('car', 'daily', 'Brown box 400', 'Brown box 400', 44),
  ('car', 'daily', 'Brown box 500', 'Brown box 500', 45),
  ('car', 'daily', 'Trolley (รถเข็น)', 'Trolley', 46),
  ('car', 'daily', 'บนคอนโซลหน้า', 'Console area', 47),
  ('car', 'daily', 'บนเบาะหน้า 2 ด้าน', 'Front seats (both sides)', 48),
  ('car', 'daily', 'ใต้เบาะหน้า 2 ด้าน', 'Under front seats (both sides)', 49),
  ('car', 'daily', 'ด้านหลังเบาะคนขับและคนนั่ง', 'Behind driver/passenger seats', 50),
  ('car', 'daily', 'ไฟในรถ', 'Interior lights', 51),
  ('car', 'daily', 'เบรคมือ', 'Hand brake', 52),
  ('car', 'daily', 'สินค้า', 'Cargo/goods', 53),
  ('car', 'daily', 'การจัดเรียง Supplies', 'Supplies arrangement', 54),
  ('car', 'daily', 'ถัง', 'Tank', 55),
  ('car', 'daily', 'ความสะอาดภายในตู้บรรทุก', 'Cargo box cleanliness', 56),
  -- Car weekly
  ('car', 'weekly', 'ถังดับเพลิง', 'Fire extinguisher', 1),
  ('car', 'weekly', 'ที่ปัดน้ำฝน', 'Windshield wipers', 2),
  ('car', 'weekly', 'ดอกยาง/ความดันลมยาง', 'Tyre tread/pressure', 3),
  -- Motorcycle daily
  ('motorcycle', 'daily', 'ไฟหน้า', 'Headlight', 1),
  ('motorcycle', 'daily', 'ไฟท้าย', 'Tail light', 2),
  ('motorcycle', 'daily', 'ไฟเลี้ยว', 'Turn signals', 3),
  ('motorcycle', 'daily', 'สัญญาณแตร', 'Horn', 4),
  ('motorcycle', 'daily', 'ยาง', 'Tyres', 5),
  ('motorcycle', 'daily', 'กระจกมองหลัง', 'Rear-view mirror', 6),
  ('motorcycle', 'daily', 'ป้ายทะเบียน', 'License plate', 7),
  ('motorcycle', 'daily', 'หมวกกันน็อค', 'Helmet', 8),
  ('motorcycle', 'daily', 'สภาพทั่วไป', 'General condition', 9),
  ('motorcycle', 'daily', 'Bike Box', 'Bike Box', 10),
  ('motorcycle', 'daily', 'Flyer (Standard & Large)', 'Flyer (Standard & Large)', 11),
  ('motorcycle', 'daily', 'Packing list Envelope', 'Packing list Envelope', 12),
  ('motorcycle', 'daily', '3 PLY Waybill', '3 PLY Waybill', 13),
  ('motorcycle', 'daily', 'Performa Invoice', 'Performa Invoice', 14),
  ('motorcycle', 'daily', 'SI Label', 'SI Label', 15),
  ('motorcycle', 'daily', 'TDX Label (Pre 9, 10:30, 12)', 'TDX Label (Pre 9, 10:30, 12)', 16),
  ('motorcycle', 'daily', 'Exception Card', 'Exception Card', 17),
  ('motorcycle', 'daily', 'Courier Notification Card', 'Courier Notification Card', 18),
  ('motorcycle', 'daily', 'OPP Tape', 'OPP Tape', 19),
  ('motorcycle', 'daily', 'Paper Envelope', 'Paper Envelope', 20),
  -- Motorcycle weekly
  ('motorcycle', 'weekly', 'ระดับน้ำมันเครื่อง', 'Engine oil level', 1),
  ('motorcycle', 'weekly', 'ดอกยาง/ความดันลมยาง', 'Tyre tread/pressure', 2),
  ('motorcycle', 'weekly', 'โซ่/สายพาน', 'Chain/belt', 3),
  ('motorcycle', 'weekly', 'ผ้าเบรค', 'Brake pads', 4),
  ('motorcycle', 'weekly', 'สภาพทั่วไปของ Bike Box', 'Bike Box condition', 5);
