INSERT INTO checklist_items (vehicle_type, frequency, item_name_th, item_name_en, sort_order) VALUES
  -- E-Van daily
  ('e_van', 'daily', 'ความสะอาดและ 5ส ทั้งภายในและภายนอกรถ', 'Cleanliness & 5S inside and outside', 1),
  ('e_van', 'daily', 'เข็มขัดนิรภัย', 'Seat belt', 2),
  ('e_van', 'daily', 'ระดับแบตเตอรี่ / สถานะการชาร์จ', 'Battery level / charge status', 3),
  ('e_van', 'daily', 'สายชาร์จและช่องเสียบชาร์จ', 'Charging cable & port', 4),
  ('e_van', 'daily', 'ประตูรถ', 'Vehicle doors', 5),
  ('e_van', 'daily', 'กระจกมองข้าง', 'Side mirrors', 6),
  ('e_van', 'daily', 'กระจกมองหลัง', 'Rear-view mirror', 7),
  ('e_van', 'daily', 'ระบบเบรค (เท้า/มือ)', 'Brakes (foot/hand)', 8),
  ('e_van', 'daily', 'ระบบสัญญาณเซ็นเซอร์ถอย', 'Reverse sensor', 9),
  ('e_van', 'daily', 'ระบบกล้องหน้า, ห้องโดยสาร', 'Front/cabin camera', 10),
  ('e_van', 'daily', 'ไฟเตือนแดชบอร์ด', 'Dashboard warning lights', 11),
  ('e_van', 'daily', 'สัญญาณแตร', 'Horn', 12),
  ('e_van', 'daily', 'ระบบกล้องหลัง', 'Rear camera', 13),
  ('e_van', 'daily', 'ไฟหรี่ - ไฟหน้า', 'Parking/head lights', 14),
  ('e_van', 'daily', 'ไฟเลี้ยว - ไฟฉุกเฉิน', 'Turn signal/hazard lights', 15),
  ('e_van', 'daily', 'ไฟระบุความสูงตู้บรรทุก', 'Cargo height indicator lights', 16),
  ('e_van', 'daily', 'ตัวถังรถ Logo และข้อความของ DHL', 'Body/DHL logo & text', 17),
  ('e_van', 'daily', 'ตัวถัง ตู้บรรทุก เสียหาย', 'Body/cargo box damage', 18),
  ('e_van', 'daily', 'ใต้ท้องรถ (รอยน้ำมันรั่ว)', 'Underbody (fluid leaks)', 19),
  ('e_van', 'daily', 'ตู้บรรทุก 7 จุด', 'Cargo box 7-point check', 20),
  ('e_van', 'daily', 'ไฟหรี่ (ด้านหลัง)', 'Rear parking lights', 21),
  ('e_van', 'daily', 'ไฟถอย - ไฟเบรค', 'Reverse/brake lights', 22),
  ('e_van', 'daily', 'ระบบ Lock และเซ็นเซอร์ประตูตู้บรรทุก', 'Cargo door lock & sensor', 23),
  ('e_van', 'daily', 'อื่นๆ (Tailgate)', 'Others (Tailgate)', 24),
  ('e_van', 'daily', 'Flyer (Standard & Large)', 'Flyer (Standard & Large)', 25),
  ('e_van', 'daily', 'Packing list Envelope', 'Packing list Envelope', 26),
  ('e_van', 'daily', '3 PLY Waybill', '3 PLY Waybill', 27),
  ('e_van', 'daily', 'Performa Invoice', 'Performa Invoice', 28),
  ('e_van', 'daily', 'SI Label', 'SI Label', 29),
  ('e_van', 'daily', 'TDX Label (Pre 9, 10:30, 12)', 'TDX Label (Pre 9, 10:30, 12)', 30),
  ('e_van', 'daily', 'Exception Card', 'Exception Card', 31),
  ('e_van', 'daily', 'Courier Notification Card', 'Courier Notification Card', 32),
  ('e_van', 'daily', 'OPP Tape', 'OPP Tape', 33),
  ('e_van', 'daily', 'Paper Envelope', 'Paper Envelope', 34),
  ('e_van', 'daily', 'Box no.2', 'Box no.2', 35),
  ('e_van', 'daily', 'Box no.3', 'Box no.3', 36),
  ('e_van', 'daily', 'Box no.4', 'Box no.4', 37),
  ('e_van', 'daily', 'Box no.5', 'Box no.5', 38),
  ('e_van', 'daily', 'Box no.6', 'Box no.6', 39),
  ('e_van', 'daily', 'Box no.7', 'Box no.7', 40),
  ('e_van', 'daily', 'Box no.8', 'Box no.8', 41),
  ('e_van', 'daily', 'Brown box 250', 'Brown box 250', 42),
  ('e_van', 'daily', 'Brown box 400', 'Brown box 400', 43),
  ('e_van', 'daily', 'Brown box 500', 'Brown box 500', 44),
  ('e_van', 'daily', 'Trolley (รถเข็น)', 'Trolley', 45),
  ('e_van', 'daily', 'ความสะอาดภายในตู้บรรทุก', 'Cargo box cleanliness', 46),
  -- E-Van weekly
  ('e_van', 'weekly', 'ถังดับเพลิง', 'Fire extinguisher', 1),
  ('e_van', 'weekly', 'ที่ปัดน้ำฝน', 'Windshield wipers', 2),
  ('e_van', 'weekly', 'ดอกยาง/ความดันลมยาง', 'Tyre tread/pressure', 3),
  ('e_van', 'weekly', 'สภาพสายชาร์จ', 'Charging cable condition', 4),
  ('e_van', 'weekly', 'ระบบปรับอากาศ', 'Air conditioning system', 5);
